### ISSUE TITLE
Compiling issues when trying to build photostream

### ISSUE THREAD

**Issue by sergioad** [derekstavis/transmission#14]
Hello I got this error when I tried to build Photostream, I have allready all the dependencies (or at least I think) and I have allready used cmake with not errors, these errors are from make:

Linking C executable photostream
CMakeFiles/photostream.dir/Widgets/PostBox.c.o: En la función `photo_stream_widgets_post_box_construct':
PostBox.c:(.text+0x1cd7): referencia a`gtk_label_set_xalign' sin definir
CMakeFiles/photostream.dir/Widgets/UserWindowBox.c.o: En la función `photo_stream_widgets_user_window_box_construct':
UserWindowBox.c:(.text+0xd68): referencia a`gtk_label_set_xalign' sin definir
CMakeFiles/photostream.dir/Widgets/CommentsBox.c.o: En la función `photo_stream_widgets_comment_box_construct':
CommentsBox.c:(.text+0xe3e): referencia a`gtk_label_set_xalign' sin definir
CMakeFiles/photostream.dir/Widgets/NewsBox.c.o: En la función `photo_stream_widgets_news_box_construct':
NewsBox.c:(.text+0x17cc): referencia a`gtk_label_set_xalign' sin definir
CMakeFiles/photostream.dir/Windows/BulkDownloadWindow.c.o: En la función `photo_stream_bulk_download_window_construct':
BulkDownloadWindow.c:(.text+0x11d8): referencia a`gtk_label_set_xalign' sin definir
collect2: error: ld returned 1 exit status
make[2]: **\* [src/photostream] Error 1
make[1]: **\* [src/CMakeFiles/photostream.dir/all] Error 2
make: **\* [all] Error 2
sergio@elementary:~/Descargas/photostream/build$

**Comment by derekstavis** [comment]
I would like to know what your bug report has to do with Transmission.

Also, you should always post programs output in English, or only people that speak your language will be able to help you.

I'm closing this issue as it's not related to this project.

**Comment by sergioad** [comment]
Ok, pardon me, wrong repo :smile:

**Comment by derekstavis** [comment]
No problem :) You are welcome to report bugs found in this repository :+1:

**Comment by sergioad** [comment]
thank you, I am getting issues compilling Transmission 3.14 too so I will report them soon :smile:
