### ISSUE TITLE
Use "search-bar" class for search toolbar

### ISSUE THREAD

**Issue by danirabbit** [derekstavis/transmission#16]
used by Adwaita and elementary themes to distinguish search bars

**Comment by derekstavis** [comment]
oh! thanks for caring! it's a great point, I'm definitely on it :)

**Comment by derekstavis** [comment]
can you give a look at how it is working on elementary now, @danrabbit ?

**Comment by danirabbit** [comment]
Looks slick! I just discovered this branch so I might end up reporting a few issues ;D
