### ISSUE TITLE
The app menu can be simplified.

### ISSUE THREAD

**Issue by me4oslav** [derekstavis/transmission#2]
So, I compiled this branch yesterday and YAY, headerbar and symbolic icons for transmission:
https://github.com/derekstavis/transmission/tree/wip/gtk-3.12
However when I opened the app menu from the top left on the gnome-shell panel I got ... well, see the attached file. As you can imagine this menu can be bug and confusing for some people and I would imagine you don't want this to happen.
![screenshot from 2015-02-12 12 05 41](https://cloud.githubusercontent.com/assets/1658870/6167464/49ec16ce-b2c4-11e4-9550-836770505526.png)
First three option are reduntant - New torrrent si already in the headerbar and you can make the "open" button in it toggle a popover with:
open file
open url
The second three can stay, although I personally see no point of the compact view mode and disabling the statusbar. Monitor nowadays are big enough. However I am not sure how will you would be to nuke these two options, because I know from experience that open source folks do enjoy having extra bells and whilstles here and there.
The third three. The Edit -> de/select all should go in the regular hamburger menu to follow the GNOME HIG. Nautilus does that and I guess you want to stick to GNOME's HIG. Start all and Pause all can stay. However the start/pause button in the headerbar should be simply for a single torrent and not a start all/pause all button.
The rest of the items are just fine.

So, what do you think of my suggestions? Cheers!

**Comment by aldomann** [comment]
Relevant links:
Application menus guidelines: https://developer.gnome.org/hig/stable/application-menus.html.en
Header bar (aka hamburger) menus guidelines: https://developer.gnome.org/hig/stable/header-bar-menus.html.en

**Comment by derekstavis** [comment]
Thanks for compiling and testing it, that's awesome! I'm planning a menu redesign and your point of view is very important.
- **Open and new actions**: They should really disappear, as you suggested.
- **Compact view and hide statusbar**: It's there for historic reasons, and I personally enjoy using both modes simultaneously, when I have lots of torrents.
- **Start/Pause/Edit**: Should disappear, it's already on headerbar.

I'm still unsure about Message Log, Statistics and Donate.

**Comment by me4oslav** [comment]
@derekstavis Thanks for the quick response! (feels odd for me to say this, when I am usually the guy that is at the receiving end of that sentence ;p)
Ace to see the huge percentage of the suggestions will be implemented, looking forward to testing the version with the redesigned menu, so do ping me here or on Google+ when they've landed. :)
Maybe next up we can redo the preferences and I've some categorisation ideas for the headerbar too.
But let's take it one step at a time and first see it with cleaned up redesigned app menu.
P.S. I don't have a lot of free time to spare, but by Jove - transmission needs UI polishing and I will try to help you as much as possible with your crusade.

**Comment by derekstavis** [comment]
@me4oslav great! there's lots of improvements to be made! thanks again!
As soon as I can get some free time to implement this changes (probably today) I ping you!

**Comment by me4oslav** [comment]
http://www.reactiongifs.com/wp-content/uploads/2014/01/fantastic.gif

**Comment by me4oslav** [comment]
Oh and shouldn't "Contents" become Help?

**Comment by derekstavis** [comment]
Yeah! So, the proposal looks like this:

---

Compact View
Status Bar
Preferences

---

Message Log
Statistics
Donate

---

Help
About
Quit

**Comment by me4oslav** [comment]
I guess this would be better:

Pause all*

---

Compact view
Status bar
Preferences

---

Message lg
Statistics
Donate

---

Hep
About 
Quit

*That should become "Start all" if all torrents are paused.

And don't forget to add the necessary headerbar fixes:
1) The open file button should open a popover with two options: "open torrent" and "open url"
2) The start/pause button on the headerbar should start/pause a single torrent, because right now there isn't a way to do that. If one wants to pause all - the top option at the appmenu is for him/her.

**Comment by derekstavis** [comment]
Makes total sense, altough I don't know how simple Start All/Pause All is to implement for a first release. Anyway, the behavior of Start/Pause button in headerbar is identical to old one and OS X Transmission client, so I don't know how acceptable it would be for users after updating.

**Comment by aldomann** [comment]
Wouldn't it be easier to implement tick boxes or any other way to have multiple selections? That would integrate much better with the GNOME HIG: https://developer.gnome.org/hig/stable/selection-mode.html.en

**Comment by derekstavis** [comment]
Selection mode would be **awesome**

**Comment by derekstavis** [comment]
About app menu, it seems great. Compiling, for a first implementation:

---

Compact View
Status Bar

---

Preferences

---

Message Log
Statistics

---

Donate
Help
About
Quit

**Comment by me4oslav** [comment]
Well, worst case scenario - keep Pause all and Start all for now.
@derekstavis Sure this is the current transmission behaviour? To not have a button for pausing or resuming a single torrent? :o I am like 101% sure it has one.
@aldomann Selections for what?

**Comment by derekstavis** [comment]
@me4oslav It has in form of a right-click popup menu. For the toolbar it's worst: It haves a button for starting and a button for pausing.

**Comment by me4oslav** [comment]
@derekstavis Yes, but these two buttons on the toolbar control the start/pause for a single torrent and not for all. Hence the start/pause button in the headerbar in here should be for single torrent too.

**Comment by aldomann** [comment]
@me4oslav for selecting multiple torrents at once and the action bar would contain: Play, Pause, Delete, Delete and Remove, Properties.

Let me do some quick mock-ups to illustrate better my idea.

**Comment by me4oslav** [comment]
@aldomann Ah, I got your idea.

**Comment by me4oslav** [comment]
@derekstavis @aldomann Ta:
![img_20150212_163251](https://cloud.githubusercontent.com/assets/1658870/6169271/15df0a42-b2d5-11e4-8005-043c7871ed2e.jpg)
![img_20150212_163259](https://cloud.githubusercontent.com/assets/1658870/6169270/15dc8696-b2d5-11e4-84e1-918d2496ded5.jpg)
Apologies about the handwriting. :)

**Comment by aldomann** [comment]
That's cheating! I was (and still am, alas) making digital wireframes.

**Comment by me4oslav** [comment]
Which is why I use the forgotten art of using pen and paper. :P
Digital stuff takes more time and in 99% of the cases hand drawn wireframes and good enough for devs.
Anyways handwriting aside, what do you guys make of these?

**Comment by aldomann** [comment]
Done! Actually, when you think about it, it makes sense to have an always active selection mode; the use of a permanent action bar is relevant in Transmisison, me thinks.
![transmission-wire](https://cloud.githubusercontent.com/assets/729732/6170189/09302c2e-b2d3-11e4-905f-b7a663b81f42.png)

The view-list button should show a popup to sort the downloads and stuff related of the view mode.

PS. The numbers and lenght of the progress bars actually add up :P

**Comment by me4oslav** [comment]
@aldomann So, here I go:
I like the always active selection mode, but why are the start, pause, properties, remove and delete and remove in a separate bar at the bottom? Can we stack the the same way I've stacked them in my headerbar wireframe. No need to waste screen space with one more bar, really. Best of both words.
What does the turtle button do? :o
The rest is ok, I guess.

**Comment by aldomann** [comment]
Man, the magic turtle!!! It limits your download/upload speeds set in your settings.
You are right about the action bar. Actually the HIG recommends not to use it if they are permanent actions. "Header bars are dynamic" so, showing the right buttons when necessary shouldn't be a problem; if there's no selected torrent, no "start/pause, delete/delete & remove, properties" buttons need to be shown. 

In the worst case scenario, those could be insensitive when not needed (no idea if the HIG recommends not to do this, though).

**Comment by me4oslav** [comment]
@aldomann,
I've never seen a turtle button before. :P Now I know what it does. 
I guess we're ok with start/pause, delete/delete and remove and properties being inactive when there is no torrent selected. They won't be of any use to be active in this case.
Just one minor thing - clicking anywhere in the space the torrent take should selected it, so users will not have to hit that pesky checkbox for a single torrent selection.
Now, create a new wireframe with all the changes. :)

**Comment by derekstavis** [comment]
Lots of great ideas! That's pretty awesome! But hey, we need to keep the discussion organizated. Let's keep this issue with comments about the Application Menu. You may create other issues for proposing alternative layouts for main window.

**Comment by me4oslav** [comment]
@derekstavis it will look even more awesome in the newest wireframe that I shamelessly dispatched Alfredo to do :)
And yes, I'll create another issue for the main window and headerbar designs. Just need the final wireframe to do so.

**Comment by derekstavis** [comment]
Great. I see we can make Transmission super-awesome. I just need to deal with technical issues in the code, and find free time to work on it. At the same time, I need to consume scope, as the first release will be the base of my term paper, that's already in progress, and I can't add more features right now :)

**Comment by me4oslav** [comment]
I don't think adding features are some sort of major concern. Transmission is in needs of a visual facelift much more than in need of new features. So don't worry about new features just yet. Let's finish the visuals first and then try to get the design upstream. Then we can start thinking for extra features.

**Comment by derekstavis** [comment]
Sorry, by extra features I meant design features :)

**Comment by derekstavis** [comment]
I need to finish my term paper, and I already defined a scope. Some fixes can be accepted, like the Application Menu and Start/Pause behavior, but I can't add major things, like selection mode, even if I think it's **awesome**. I hope you guys understand this and have some patience before I can start working on more visual facelifts :)

**Comment by me4oslav** [comment]
Ah. :P
Well, we can take it one step at a time, it is not like any of us is getting paid for this, so we can pull of a Danny Boy (Daniel from elementary, why I call him Danny Boy is a long story) and adopt the "when it's ready" agenda. Plus knowing myself and Alfredo we can popularise the designs when we finish them and maybe attract devs to help you.

**Comment by derekstavis** [comment]
I just started on OSS, my mission is to GTKalize and CSDlize everything, but I don't have any developer network to help me with this :)

**Comment by me4oslav** [comment]
We can try to lure dev hamsters, but no promises given that it will actually work. But it is worth a shot, because open source can surely use less sucky design.

**Comment by aldomann** [comment]
@derekstavis that's also my mission (although I'm no developer)! Check my deviantArt page: http://aldomann.deviantart.com/gallery/

We (@me4oslav and me)  can help you with designs any time you need :)

**Comment by derekstavis** [comment]
I like to design and like to develop. We will probably get best friends :+1:

**Comment by me4oslav** [comment]
And my mission is to keep Starling City safe. :D
I very mmuch enjoy sleeping. And drinking. And eating. And reading. In no specific order.
@aldomann Waiting for that new wireframe for the main layout and headerbar.

**Comment by derekstavis** [comment]
I sleep a lot too. That's why Transmission isn't yet ready.

**Comment by aldomann** [comment]
@me4oslav http://aldomann.deviantart.com/art/Transmission-GTK-3-CSD-redesign-513447880

**Comment by derekstavis** [comment]
Also, this code is old. It doesn't even use builder XML.

**Comment by me4oslav** [comment]
@derekstavis Sleeping is absolutely brilliant. :)
@aldomann Just add the appmenu there.

**Comment by me4oslav** [comment]
Ta - https://github.com/derekstavis/transmission/issues/3

**Comment by derekstavis** [comment]
App menu was simplified. You can check it on branch `wip/gtk3.14`.
