### ISSUE TITLE
Main pane and headerbar redesign

### ISSUE THREAD

**Issue by me4oslav** [derekstavis/transmission#3]
Wireframes:
http://aldomann.deviantart.com/art/Transmission-GTK-3-CSD-redesign-513447880

Headerbar description:
- Open button opens a popover with two options:
  - Open torrent
  - Open url
    The + button will take you to the create new torrent dialog.
    The looking glass is evidently "Search".
    The turtle button limits the download and upload speed to the one set in the preferences.
    The rest is pretty much explained.

Main pane description:
- Transmission is always in "select mode" so you can select and start/pause remove/remmove and delete a single torrent or multiple ones just by clicking on the checkboxes.
- Selecting one torrent can also happen by clicking anywhere its personal pane and not just on the checkbox..Of course ctrl / shift + clicking on the pane space will act like ctrl / shift clicking on a checkbox.

Issues: 
- Start AND pause buttons.
- The progress bar issue with uploading having better ration than downloading.

Extra:
- Appmenu redesign talk: https://github.com/derekstavis/transmission/issues/2

**Comment by aldomann** [comment]
As modified in the wireframe, the "Delete and Remove" action can be simplified by adding a tick box in the "Remove torrent" dialogue. It can be confusing to have two buttons that do essentially the same.

**Comment by aldomann** [comment]
About Play/Pause. How about showing Play if all selected torrents are paused; Pause if all selected torrents are downloading/seeding; Play & Pause if it's a mix of both (this is vaguely implied in the wireframe).

I think the Properties action should be as in the updated wireframe. Inspired in the current Network Settings. It makes sense, since you really don't want to open the properties dialogue of multiple files, but one at a time.

**Comment by me4oslav** [comment]
I agree about the properties. You're just using the wrong symbolic icon for it. You need to change the cog to "document-properties-symbolic" or perhaps it was "document-preferences-symbolic".
Agreed about the remove thing. Didn't show the right wireframe. Sorry.
Play/Pause - I agree, but fix the wireframe, because I got really confused without the extra explanation. :)

**Comment by me4oslav** [comment]
So to summarise there are four issues to fix in the wireframes:

How to select all torrent with a click or two? Marking them all or using ctrl+a are the two only options.
That cog is supposed to be the document-properties icon.
The play/pause UX needs fixing in the wireframe as decided in the first three comments.
What is the point of the first wireframe?

**Comment by aldomann** [comment]
The point is to... erm... show the... let's kill it :P
Already updated the wireframe.

**Comment by me4oslav** [comment]
We still miss fast mouse way to select all torrent. Perhaps in right click on torrent menu we should have select all / deselct all item? (If selected - deselect and vice versa)
Not sure that dynamic thing is possible to code though or even if it is - won't be be safer to just make button inactive when they are not needed.

**Comment by derekstavis** [comment]
Yes @me4oslav. I have been using Ctrl+A, but obviously it's not obvious.

**Comment by me4oslav** [comment]
Hence I suggest we shove it in the context menu too. I always add design way for even the dumbest of users. Call it a safety insurance. :)

**Comment by derekstavis** [comment]
The users isn't really dumb. They just think the things are were they isn't.

**Comment by aldomann** [comment]
Precisely, and that's one of the things the new GNOME HIG solves in a way: what you see is pretty much what the application can do; no ridiculously hidden features and overcomplicated menus.

**Comment by derekstavis** [comment]
GNOME HIG is awesome. Did I mention it was the spark for this redesign?

**Comment by me4oslav** [comment]
Balkan genes, I tend to not always use the polite words. :)

**Comment by me4oslav** [comment]
Ok, the latest version of the wireframes fixes all the issues we found out:
http://aldomann.deviantart.com/art/Transmission-GTK-3-CSD-redesign-513447880
Siiiiiiiiiiiii.

**Comment by derekstavis** [comment]
I still think that purple progress is a issue. We should put this in the backlog for further discussion. If the ratio passes 1, it will overlay the actual progress of the download.

**Comment by me4oslav** [comment]
That and the pause and start buttons.

**Comment by aldomann** [comment]
@derekstavis true that, sir. It's not a really necessary feature, as I have said before, I limited myself to copypaste the behaviour of this extension: https://extensions.gnome.org/extension/365/transmission-daemon-indicator/

If it's too problematic we could nuke it; but it certainly may come in handy in certain situations. We should rethink the implementation if we want to include it, definitely.

**Comment by derekstavis** [comment]
Yeah, they must be well discussed. That's why for the first milestone I will be deploying a start/stop all torrents button. You can start/stop only one via right click. We need to do gradual UI changes to not scare users.

**Comment by me4oslav** [comment]
There is some Pull Request to look at.
About the uploading bar - we can always have it as another progressbar.

**Comment by aldomann** [comment]
And it could be just an option from the settings.

**Comment by me4oslav** [comment]
@derekstavis For milestone 1, lets have the start/stop work for a single torrent and keep the start all and pause all in the the appmenu. It is silly to not have pausing a single torrent option at obvious place. Pausing one torrent is much more common than pausing all of them.

**Comment by me4oslav** [comment]
If we agree to go with my suggestion above (and it honestly makes a lot of sense) then this pull request - https://github.com/derekstavis/transmission/pull/5 must restore the start/pause all buttons in the appmenu before it can be grrenlit for merging design wise.

**Comment by derekstavis** [comment]
Ok, I'm reviewing pull requests before merging. Thanks for the PRs @evfool

**Comment by danirabbit** [comment]
Movement on this report seems to have kind of died. @me4oslav is there any way you can modify this report to include check items for individual issues remaining or maybe create a milestone and target separate issues? Just some way to see what work there is left to do here? I don't want to be making duplicate reports ;)
- [ ] check items

**Comment by derekstavis** [comment]
Thanks Daniel for refreshing this issue. I prefer us to keep more organized, by creating new issues for every redesign point, so I'm closing this issue.

**Comment by danirabbit** [comment]
Sounds good to me! I'll try to look through his mockups and make new issues related to differences I can spot

**Comment by derekstavis** [comment]
Thanks for your dedication, Daniel Foré.

**Comment by danirabbit** [comment]
No problem! I'm definitely interested in seeing this branch progress :)

**Comment by killhellokitty** [comment]
The latest version does'nt show a Gui.  It starts without one.  However the web interface works.
