### ISSUE TITLE
Get rid of the statusbar

### ISSUE THREAD

**Issue by evfool** [derekstavis/transmission#7]
On the designs the statusbar does not exist anymore.

The components needing from the statusbar are:
- setting custom speed limits
- alternative speed limits (50 kb/s upload and download) => moved to header bar in the design
- current download speed, upload speed => moved to header bar subtitle in the design
- statistics label => not seen anywhere on the design, but info can be found from appmenu->statistics
- statistics type selection button => no need for this, as everything is available in appmenu->statistics

These widgets should be moved/removed to their new places in order to get rid of the statusbar.

**Comment by aldomann** [comment]
If you check the updated wireframe (http://aldomann.deviantart.com/art/Transmission-GTK-3-CSD-redesign-513447880), you'll notice we've moved all Alternative Downloads settings to the Tortoise menu, which acts as an indicator of "Enabled Alternative Speed Limits" and as a popover.

With these changes, I think we can get rid of the status bar.

**Comment by derekstavis** [comment]
We decided to keep the status bar for the time being.
